package com.fabrizioroot.vertal.service;
import com.fabrizioroot.vertal.dto.*; import com.fabrizioroot.vertal.exception.*; import com.fabrizioroot.vertal.model.*; import com.fabrizioroot.vertal.repository.*; import org.springframework.stereotype.Service; import java.util.*;
@Service public class TaskService {
 private final TareaRepository tareas; private final EquipoRepository equipos; private final UsuarioRepository usuarios; private final AsignacionRepository asignaciones; private final RecordatorioRepository recordatorios; private final AuthorizationService auth;
 public TaskService(TareaRepository t,EquipoRepository e,UsuarioRepository u,AsignacionRepository a,RecordatorioRepository r,AuthorizationService x){tareas=t;equipos=e;usuarios=u;asignaciones=a;recordatorios=r;auth=x;}
 public TaskResponseDto create(Long uid,TaskRequestDto dto){Usuario u=auth.current(uid);Equipo e=equipos.findById(dto.equipoId()).orElseThrow(()->new ResourceNotFoundException("Equipo no encontrado"));auth.memberOrManager(u,e);Tarea t=new Tarea();t.setTitulo(dto.titulo());t.setDescripcion(dto.descripcion());t.setFechaVencimiento(dto.fechaVencimiento());t.setEquipo(e);t.setCreador(u);return to(tareas.save(t));}
 public List<TaskResponseDto> list(Long uid){Usuario u=auth.current(uid);List<Long> ids=new ArrayList<>();for(Equipo e:equipos.findAll())if(e.getOrganizacion().getId().equals(u.getOrganizacion().getId())&&auth.isMember(uid,e))ids.add(e.getId());return tareas.findByEquipoIdInAndActivaTrue(ids).stream().map(this::to).toList();}
 public TaskResponseDto get(Long uid,Long id){Tarea t=find(id);auth.memberOrManager(auth.current(uid),t.getEquipo());return to(t);}
 public TaskResponseDto update(Long uid,Long id,TaskRequestDto dto){Tarea t=find(id);auth.managerOrCreator(auth.current(uid),t.getEquipo());t.setTitulo(dto.titulo());t.setDescripcion(dto.descripcion());t.setFechaVencimiento(dto.fechaVencimiento());return to(tareas.save(t));}
 public void delete(Long uid,Long id){Tarea t=find(id);auth.managerOrCreator(auth.current(uid),t.getEquipo());t.setActiva(false);tareas.save(t);}
 public void assign(Long uid,Long id,AssignmentRequestDto dto){Tarea t=find(id);auth.managerOrCreator(auth.current(uid),t.getEquipo());Usuario u=usuarios.findById(dto.usuarioId()).orElseThrow(()->new ResourceNotFoundException("Usuario no encontrado"));if(!authMember(u.getId(),t.getEquipo()))throw new BadRequestException("El usuario no pertenece al equipo");if(asignaciones.existsByTareaIdAndUsuarioAsignadoId(id,u.getId()))throw new ConflictException("La tarea ya está asignada");Asignacion a=new Asignacion();a.setTarea(t);a.setUsuarioAsignado(u);asignaciones.save(a);}
 public TaskResponseDto status(Long uid,Long id,StatusUpdateRequestDto dto){Tarea t=find(id);auth.assignedOrManager(auth.current(uid),t);t.setEstado(dto.estado());return to(tareas.save(t));}
 public TaskResponseDto complete(Long uid,Long id){return status(uid,id,new StatusUpdateRequestDto(EstadoTarea.COMPLETADA));}
 public ReminderResponseDto reminder(Long uid,Long id,ReminderRequestDto dto){Tarea t=find(id);Usuario u=auth.current(uid);auth.assignedOrManager(u,t);Recordatorio r=new Recordatorio();r.setTarea(t);r.setUsuario(u);r.setFechaHora(dto.fechaHora());return to(recordatorios.save(r));}
 public List<ReminderResponseDto> reminders(Long uid,Long id){Tarea t=find(id);auth.memberOrManager(auth.current(uid),t.getEquipo());return recordatorios.findByTareaIdAndActivoTrue(id).stream().map(this::to).toList();}
 public void removeReminder(Long uid,Long rid){Recordatorio r=recordatorios.findById(rid).orElseThrow(()->new ResourceNotFoundException("Recordatorio no encontrado"));if(!r.getUsuario().getId().equals(uid))throw new UnauthorizedOperationException("No puede eliminar este recordatorio");r.setActivo(false);recordatorios.save(r);}
 private Tarea find(Long id){return tareas.findById(id).filter(Tarea::isActiva).orElseThrow(()->new ResourceNotFoundException("Tarea no encontrada"));} private boolean authMember(Long uid,Equipo e){return auth.isMember(uid,e);}
 private TaskResponseDto to(Tarea t){return new TaskResponseDto(t.getId(),t.getTitulo(),t.getDescripcion(),t.getFechaCreacion(),t.getFechaVencimiento(),t.getEstado(),t.getEquipo().getId(),t.getCreador().getId());} private ReminderResponseDto to(Recordatorio r){return new ReminderResponseDto(r.getId(),r.getTarea().getId(),r.getUsuario().getId(),r.getFechaHora(),r.isActivo());}
}