package com.fabrizioroot.vertal.service;
import com.fabrizioroot.vertal.dto.*; import com.fabrizioroot.vertal.exception.*; import com.fabrizioroot.vertal.model.*; import com.fabrizioroot.vertal.repository.*; import org.springframework.stereotype.Service; import java.util.*;
@Service public class TeamService {
 private final EquipoRepository equipos; private final OrganizacionRepository organizaciones; private final UsuarioRepository usuarios; private final MembresiaEquipoRepository membresias; private final AuthorizationService auth;
 public TeamService(EquipoRepository e,OrganizacionRepository o,UsuarioRepository u,MembresiaEquipoRepository m,AuthorizationService a){equipos=e;organizaciones=o;usuarios=u;membresias=m;auth=a;}
 public TeamResponseDto create(Long uid,TeamRequestDto dto){Usuario u=auth.current(uid);auth.canOperate(u);Equipo e=new Equipo();e.setNombre(dto.nombre());e.setCreador(u);e.setOrganizacion(u.getOrganizacion());Equipo saved=equipos.save(e);MembresiaEquipo m=new MembresiaEquipo();m.setUsuario(u);m.setEquipo(saved);membresias.save(m);return to(saved);}
 public List<TeamResponseDto> list(Long uid){Usuario u=auth.current(uid);return equipos.findAll().stream().filter(e->e.isActivo()&&e.getOrganizacion().getId().equals(u.getOrganizacion().getId())&&(e.getCreador().getId().equals(uid)||membresias.existsByUsuarioIdAndEquipoIdAndActivaTrue(uid,e.getId()))).map(this::to).toList();}
 public TeamResponseDto get(Long uid,Long id){Equipo e=equipos.findById(id).orElseThrow(()->new ResourceNotFoundException("Equipo no encontrado"));auth.memberOrManager(auth.current(uid),e);return to(e);}
 public void add(Long uid,Long teamId,MemberRequestDto dto){Usuario actor=auth.current(uid);Equipo e=equipos.findById(teamId).orElseThrow(()->new ResourceNotFoundException("Equipo no encontrado"));auth.managerOrCreator(actor,e);Usuario member=usuarios.findById(dto.usuarioId()).orElseThrow(()->new ResourceNotFoundException("Usuario no encontrado"));if(membresias.existsByUsuarioIdAndEquipoIdAndActivaTrue(member.getId(),teamId))throw new ConflictException("El usuario ya pertenece al equipo");MembresiaEquipo m=membresias.findByUsuarioIdAndEquipoId(member.getId(),teamId).orElseGet(MembresiaEquipo::new);m.setUsuario(member);m.setEquipo(e);m.setActiva(true);membresias.save(m);}
 public void remove(Long uid,Long teamId,Long memberId){Usuario actor=auth.current(uid);Equipo e=equipos.findById(teamId).orElseThrow(()->new ResourceNotFoundException("Equipo no encontrado"));auth.managerOrCreator(actor,e);MembresiaEquipo m=membresias.findByUsuarioIdAndEquipoId(memberId,teamId).orElseThrow(()->new ResourceNotFoundException("Membresía no encontrada"));m.setActiva(false);membresias.save(m);}
 private TeamResponseDto to(Equipo e){return new TeamResponseDto(e.getId(),e.getNombre(),e.getFechaCreacion(),e.getCreador().getId());}
}