package com.fabrizioroot.vertal.controller;
import com.fabrizioroot.vertal.dto.*; import com.fabrizioroot.vertal.exception.*; import com.fabrizioroot.vertal.model.*; import com.fabrizioroot.vertal.repository.*; import com.fabrizioroot.vertal.service.*; import jakarta.validation.Valid; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/admin") public class AdminController {
 private final AuthService auth; private final AuthorizationService authorization; private final SolicitudVinculacionRepository solicitudes; private final UsuarioRepository usuarios; private final VinculacionDispositivoRepository vinculaciones;
 public AdminController(AuthService a,AuthorizationService x,SolicitudVinculacionRepository s,UsuarioRepository u,VinculacionDispositivoRepository v){auth=a;authorization=x;solicitudes=s;usuarios=u;vinculaciones=v;}
 private Usuario admin(Long id){Usuario u=authorization.current(id);if(!authorization.isAdmin(u))throw new UnauthorizedOperationException("Solo el administrador de sistemas");return u;}
 @GetMapping("/linking/requests") public List<LinkingResponseDto> requests(@AuthenticationPrincipal Long id){Usuario u=admin(id);return solicitudes.findByOrganizacionIdOrderByFechaSolicitudDesc(u.getOrganizacion().getId()).stream().map(s->new LinkingResponseDto(s.getId(),s.getNombreUsuarioSolicitado(),s.getEstado(),s.getFechaSolicitud(),null)).toList();}
 @PostMapping("/linking/requests/{id}/approve") public LinkingResponseDto approve(@AuthenticationPrincipal Long uid,@PathVariable Long id,@Valid @RequestBody ApproveLinkingRequestDto dto){return auth.approve(id,admin(uid),dto);}
 @PostMapping("/linking/requests/{id}/reject") public LinkingResponseDto reject(@AuthenticationPrincipal Long uid,@PathVariable Long id){return auth.reject(id,admin(uid));}
 @GetMapping("/users") public List<UserResponseDto> users(@AuthenticationPrincipal Long id){Usuario admin=admin(id);return usuarios.findAll().stream().filter(u->u.getOrganizacion().getId().equals(admin.getOrganizacion().getId())).map(u->new UserResponseDto(u.getId(),u.getNombreUsuario(),u.getNombreCompleto(),u.getRol(),u.isActivo())).toList();}
 @PutMapping("/users/{id}/role") public UserResponseDto role(@AuthenticationPrincipal Long uid,@PathVariable Long id,@Valid @RequestBody AssignRoleRequestDto dto){admin(uid);Usuario u=usuarios.findById(id).orElseThrow(()->new ResourceNotFoundException("Usuario no encontrado"));u.setRol(dto.rol());u=usuarios.save(u);return new UserResponseDto(u.getId(),u.getNombreUsuario(),u.getNombreCompleto(),u.getRol(),u.isActivo());}
 @DeleteMapping("/users/{id}") public void deactivate(@AuthenticationPrincipal Long uid,@PathVariable Long id){admin(uid);Usuario u=usuarios.findById(id).orElseThrow(()->new ResourceNotFoundException("Usuario no encontrado"));u.setActivo(false);usuarios.save(u);vinculaciones.findByUsuarioIdAndActivaTrue(id).forEach(v->{v.setActiva(false);vinculaciones.save(v);});}
}